### ISSUE TITLE
Tensorflow-2

### ISSUE THREAD

**Issue by Amin-Tgz** [adhiraiyan/DeepLearningWithTF2.0#1]
Hello,
I'm one of the fans of Tensorflow-2 and have created a [repository](https://github.com/Amin-Tgz/Awesome-TensorFlow-2) to collect the best of resources available which use this version.
Recently I saw your fantastic repository and notebooks about TF v2.0.
So I add this to my repo. I appreciate if you can help me to collect other stuff you think might be useful
Thanks.

**Comment by mukeshmithrakumar** [comment]
Yeah @Amin-Tgz, sorry for the late reply and thank you for reaching out.

Would love to help you out. I am working with the TF 2.0 team so I often get updates on blog posts and the like, it should be somewhere in my emails, I have some deadlines during the week so would collect it and make a pull request to your repo during the weekend

**Comment by Amin-Tgz** [comment]
Thank you so much :)

**Comment by mukeshmithrakumar** [comment]
Hi @Amin-Tgz , I created three pull requests, added two blog posts and a code repo link, will update more as we finalize more blog posts and codes in tf 2.0
