### ISSUE TITLE
Hello, where can I read this book

### ISSUE THREAD

**Issue by zcdliuwei** [adhiraiyan/DeepLearningWithTF2.0#2]

**Comment by mukeshmithrakumar** [comment]
Hi @zcdliuwei , you can read it:
- https://www.adhiraiyan.org/category/deeplearning/ in my blog or
- https://nbviewer.jupyter.org/github/adhiraiyan/DeepLearningWithTF2.0/blob/master/notebooks/Index.ipynb
which is in notebook format
